const Terms = () => {
  return (
    <>
      <h2>Terms & Conditions and Privacy Policy</h2>

      <h3>Cookies</h3>

      <p>
        When you are signed in, a cookie is used to track who you are; it
        contains a simple unique string used to identify your requests.
      </p>

      <p>
        If a 3rd person gets a hold of this cookie, they can gain access to your
        account. It is as secure as your browser is.
      </p>

      <h3>Local Storage</h3>

      <p>We use local storage to hold data that we deem low security.</p>

      <h3>IP Addresses</h3>

      <p>
        Your IP address is recorded with your chat messages for a time period;
        it is accessible to admins of the website.
      </p>

      <h3>Use of Google, Discord and Twitch User Data</h3>

      <p>
        You have the option of signing up for chudlogic.com with your Google,
        Discord or Twitch account. As part of the sign up process, chudlogic.com
        will obtain data from Google, Discord or Twitch that allows it to
        uniquely identify you. This includes your Google, Discord or Twitch
        account's primary email address, and a unique identifier for the account
        generated by Google, Discord or Twitch. This data is used to link you to
        your chudlogic.com account and allows for future sign ins so long as you
        have access to your Google, Discord or Twitch account.
      </p>

      <h2>Account Deletion</h2>

      <p>
        You can request account removal via your profile. We will action this
        within 30 days of your submission.
      </p>

      <h2>Data Access</h2>

      <p>
        Any user may request a full output of their data at any point. An admin
        will provide these details within a reasonable amount of time.
      </p>

      <h2>User Agreement</h2>

      <p>
        You must not attempt to gain access to data or user accounts that are
        not yours.
      </p>

      <p>You must not create user profiles using automated code.</p>

      <h2>Rights Reserved</h2>

      <p>We may change these and others rules on the website.</p>

      <p>We may block or delete your account when appropriate.</p>

      <p>We may or may not issue refunds on subscriptions or donations.</p>

      <p>
        We may or may not respond to questions and or bug reports regarding this
        website, within whatever time frame we can afford.
      </p>
    </>
  );
};

export default Terms;
