import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import {
  faClipboardList,
} from '@fortawesome/free-solid-svg-icons';
import Contact from '@/components/contact';

const Terms = () => {
  return (
    <>
    <section className="grid grid-cols-1 md:grid-cols-3 gap-5">
      <section className="bg-black/20 border border-zinc-800 rounded p-5 md:col-span-2 text-justify">
        <h2 className="mb-2.5 text-3xl font-black uppercase italic">
          <FontAwesomeIcon icon={faClipboardList} className="mr-1 text-vomit-500" />
          Terms & Conditions
        </h2>

        <h3 className="mb-2.5 mt-2.5 text-xl font-black uppercase">Cookies</h3>

        <p className="mb-2.5">
          When you are signed in, a cookie is used to track who you are; it
          contains a simple unique string used to identify your requests.
        </p>

        <p className="mb-2.5">
          If a 3rd person gets a hold of this cookie, they can gain access to
          your account. It is as secure as your browser is.
        </p>

        <h3 className="mb-2.5 mt-2.5 text-xl font-black uppercase">Local Storage</h3>

        <p className="mb-2.5">
          We use local storage to hold data that we deem low security.
        </p>

        <h3 className="mb-2.5 mt-2.5 text-xl font-black uppercase">IP Addresses</h3>

        <p className="mb-2.5">
          Your IP address is recorded with your chat messages for a time period;
          it is accessible to admins of the website.
        </p>

        <h3 className="mb-2.5 mt-2.5 text-xl font-black uppercase">Use of Google, Discord and Twitch User Data</h3>

        <p className="mb-2.5">
          You have the option of signing up for chudlogic.com with your Google,
          Discord or Twitch account. As part of the sign up process,
          chudlogic.com will obtain data from Google, Discord or Twitch that
          allows it to uniquely identify you. This includes your Google, Discord
          or Twitch account's primary email address, and a unique identifier for
          the account generated by Google, Discord or Twitch. This data is used
          to link you to your chudlogic.com account and allows for future sign
          ins so long as you have access to your Google, Discord or Twitch
          account.
        </p>

        <h2 className="mb-2.5 mt-2.5 text-xl font-black uppercase">Account Deletion</h2>

        <p className="mb-2.5">
          You can request account removal via your profile. We will action this
          within 30 days of your submission.
        </p>

        <h2 className="mb-2.5 mt-2.5 text-xl font-black uppercase">Data Access</h2>

        <p className="mb-2.5">
          Any user may request a full output of their data at any point. An
          admin will provide these details within a reasonable amount of time.
        </p>

        <h2 className="mb-2.5 mt-2.5 text-xl font-black uppercase">User Agreement</h2>

        <p className="mb-2.5">
          You must not attempt to gain access to data or user accounts that are
          not yours.
        </p>

        <p className="mb-2.5">
          You must not create user profiles using automated code.
        </p>

        <h2 className="mb-2.5 mt-2.5 text-xl font-black uppercase">Rights Reserved</h2>

        <p className="mb-2.5">
          We may change these and others rules on the website.
        </p>

        <p className="mb-2.5">
          We may block or delete your account when appropriate.
        </p>

        <p className="mb-2.5">
          We may or may not issue refunds on subscriptions or donations.
        </p>

        <p className="mb-2.5">
          We may or may not respond to questions and or bug reports regarding
          this website, within whatever time frame we can afford.
        </p>
      </section>
      <aside className="bg-black/20 border border-zinc-800 rounded p-5 h-fit">
        <Contact />
      </aside>
      </section>
    </>
  );
};

export default Terms;
